apiVersion: v1
kind: Service
namespace: nginx-app
metadata:
  name: nginx-app-service
  labels:
    run: nginx-app-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx-app
